CREATE TABLE active (
	as_of_date date, 
	member_last_name varchar, 
	member_first_name varchar, 
	member_mi varchar, 
	-- birth_year integer, 
	enrollment_date date, 
	employer_name varchar, 
	location_code integer, 
	location_name varchar, 
	pension_fund_id integer, 
	pension_fund_name varchar, 
	pension_group_id varchar, 
	pension_group_name varchar, 
	veteran_status varchar, 
	service_years_qty integer, 
	service_months_qty integer, 
	total_months_qty integer, 
	current_employer_salary_amt money, 
	all_employers_salary_amt money, 
	"25_year_date" date, 
	"20_year_status" boolean, 
	membership_tier integer
);
